### PR TITLE
[Review Needed] Add FAQ to docs

### PR DESCRIPTION
**Pull request by Jerry23011**

### CODE REVIEW

**Comment by tisfeng** [comment]
Seems something is wrong when I run it locally 🥲

```shell
npx vitepress dev 
```

image

**Comment by yangg** [comment]
the `<td>` tag should has close end tag

```
<td> <img src="https://raw.githubusercontent.com/tisfeng/ImageBed/main/uPic/image-20230708115811617-1688788691.png">

=>

<td> <img src="https://raw.githubusercontent.com/tisfeng/ImageBed/main/uPic/image-20230708115811617-1688788691.png"></td>

```

**Review by yangg — COMMENTED** [review]
all `<td>` should add `</td>` to close tag

**Comment by tisfeng** [comment]
> all `<td>` should add `</td>` to close tag

Ok, fixed.

**Review by yangg — DISMISSED** [review]

**Comment by yangg** [comment]
> > all `<td>` should add `</td>` to close tag
> 
> Ok, fixed.

I cannot open the deploy link, please provide the  failed log.

**Comment by tisfeng** [comment]
```
[11:15:16.415] Running build in Washington, D.C., USA (East) – iad1
[11:15:16.546] Cloning github.com/tisfeng/easydict-docs (Branch: faq, Commit: de525e3)
[11:15:16.565] Skipping build cache, deployment was triggered without cache.
[11:15:16.916] Cloning completed: 370.271ms
[11:15:17.203] Running "vercel build"
[11:15:17.722] Vercel CLI 33.5.3
[11:15:18.500] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8
[11:15:18.512] Installing dependencies...
[11:15:19.172] Lockfile is up to date, resolution step is skipped
[11:15:19.192] Progress: resolved 1, reused 0, downloaded 0, added 0
[11:15:19.213] Packages: +73
[11:15:19.213] +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[11:15:20.194] Progress: resolved 73, reused 0, downloaded 51, added 39
[11:15:20.794] Progress: resolved 73, reused 0, downloaded 73, added 73, done
[11:15:20.856] .../node_modules/vue-demi postinstall$ node ./scripts/postinstall.js
[11:15:20.982] .../node_modules/vue-demi postinstall: Done
[11:15:20.994] .../esbuild@0.19.12/node_modules/esbuild postinstall$ node install.js
[11:15:21.065] .../esbuild@0.19.12/node_modules/esbuild postinstall: Done
[11:15:21.140] 
[11:15:21.141] devDependencies:
[11:15:21.142] + vitepress 1.0.0-rc.40
[11:15:21.142] 
[11:15:21.146] Done in 2.5s
[11:15:21.481] 
[11:15:21.482]   [32m[1mvitepress[22m v1.0.0-rc.40[39m
[11:15:21.483] 
[11:15:21.527] - building client + server bundles...
[11:15:22.713] [31m[vite:vue] Element is missing end tag.[39m
[11:15:22.714] file: [36m/vercel/path0/zh/guide/faq.md:39:5[39m
[11:15:22.714] [31m✖[0m building client + server bundles...
[11:15:22.781] [31mbuild error:[39m
[11:15:22.781] SyntaxError: Element is missing end tag.
[11:15:22.781]     at createCompilerError (/vercel/path0/node_modules/.pnpm/@vue+compiler-core@3.4.15/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:1328:17)
[11:15:22.782]     at emitError (/vercel/path0/node_modules/.pnpm/@vue+compiler-core@3.4.15/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:2788:5)
[11:15:22.782]     at Object.onclosetag (/vercel/path0/node_modules/.pnpm/@vue+compiler-core@3.4.15/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:2182:13)
[11:15:22.782]     at Tokenizer.stateInClosingTagName (/vercel/path0/node_modules/.pnpm/@vue+compiler-core@3.4.15/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:750:16)
[11:15:22.782]     at Tokenizer.parse (/vercel/path0/node_modules/.pnpm/@vue+compiler-core@3.4.15/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:1110:16)
[11:15:22.783]     at Object.baseParse (/vercel/path0/node_modules/.pnpm/@vue+compiler-core@3.4.15/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:2820:13)
[11:15:22.783]     at Object.parse (/vercel/path0/node_modules/.pnpm/@vue+compiler-dom@3.4.15/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.prod.js:633:23)
[11:15:22.783]     at Object.parse$2 [as parse] (/vercel/path0/node_modules/.pnpm/@vue+compiler-sfc@3.4.15/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:1851:24)
[11:15:22.783]     at createDescriptor (file:///vercel/path0/node_modules/.pnpm/@vitejs+plugin-vue@5.0.3_vite@5.0.12_vue@3.4.15/node_modules/@vitejs/plugin-vue/dist/index.mjs:74:43)
[11:15:22.784]     at transformMain (file:///vercel/path0/node_modules/.pnpm/@vitejs+plugin-vue@5.0.3_vite@5.0.12_vue@3.4.15/node_modules/@vitejs/plugin-vue/dist/index.mjs:2367:34)
[11:15:22.796] Error: Command "vitepress build" exited with 1
[11:15:22.999] 
```

**Comment by yangg** [comment]
try 
```<br class="Apple-interchange-newline" />```

**Comment by tisfeng** [comment]
> <br class="Apple-interchange-newline" />

Sorry, I can't understand, please tell me exactly how to do it, or you can just come to modify it in PR.

**Comment by tisfeng** [comment]
> try `<br class="Apple-interchange-newline" />`

Sorry, I can't understand, please tell me exactly how to do it, or you can just come to modify it in PR.

**Comment by yangg** [comment]
image

**Comment by tisfeng** [comment]
It's so annoying, I don't know why CI keeps reporting errors when using `<table>`, I have no problem running it locally.

I just removed `<td>` tag,  use the markdown syntax directly to display image, now it works successfully. https://github.com/tisfeng/easydict-docs/pull/1/commits/380db3863c3e917beb7aeb9fa415fe1ffd862b14

In addition, I found that in such a compact document page, the full image looks better than `<table>`.

**Review by tisfeng — APPROVED** [review]

**Comment by Jerry23011** [comment]
Thank you everyone

**Pull request merged**
